// Dish names & prices sourced from https://anuskitchendublin.com/order-now/.
// Descriptions, ingredients, and allergens are researched estimates — NOT
// confirmed by the restaurant. Allergen numbers below are only populated where
// the research was unambiguous (no "possible"/"if used" hedging); anything
// uncertain is deliberately left blank rather than guessed, since this is a
// real food-safety concern, not a UX detail. Get kitchen sign-off before going live.
// AR models: real per-dish scans pulled in for the dishes the kitchen has
// photographed so far. Everything else still has none — no fake/shared
// placeholder model, so no AR badge shows until a real scan exists for it.
// `scale` starts at 0.35 0.35 0.35 for all of them (0.2 baseline corrected
// for real-world AR size, then bumped ~1.75x per feedback on perceived size).
// Not verified on a real device per dish yet — check actual AR placement size
// and adjust per-model if off.

const ALLERGEN = { CRUSTACEAN: 2, FISH: 4, SOY: 6, MOLLUSC: 14, GLUTEN: 1 };

const restaurant = {
  subdomain: 'anuskitchen',
  name:      "Anu's Kitchen",
  tagline:   'Authentic Nigerian Cuisine',
  eyebrow:   "Dublin's Finest Nigerian Kitchen",

  theme: {
    '--bg':         '#FEF7EE',
    '--header-bg':  '#1C0A00',
    '--accent':     '#C8860A',
    '--accent-dark':'#9A6408',
    '--text':       '#1C0A00',
    '--text-muted': '#7A5C48',
    '--card-bg':    '#FFFFFF',
    '--border':     '#EDD9C0',
    '--badge-bg':   '#FFF3DC',
    '--badge-text': '#92570A',
  },

  categories: ['Rice Dishes', 'Soups & Swallow', 'Pepper Soup', 'Grills & Sides', 'Seafood', 'Other Favourites'],

  dishes: [
    // ── Rice Dishes ──
    {
      key:         'jollof-rice-plantain',
      name:        'Jollof Rice & Plantain',
      category:    'Rice Dishes',
      price:       '€18.00',
      description: 'The classic tomato-based party jollof rice, slow-cooked with peppers and spices, served with sweet fried plantain.',
      tags:        ['Nigerian Classic', 'Popular'],
      image:       '/assets/images/jollof-rice-plantain.jpg',
      placeholder: { gradient: 'linear-gradient(145deg, #8B1A00 0%, #C8490A 45%, #E07020 100%)', emoji: '🍛' },
      model:       '/assets/models/jollof-rice-plantain.glb',
      scale:       '0.35 0.35 0.35',
      allergens:   [],
      portion:     'A full plate of rice with a generous side of fried plantain.',
      ingredients: 'Rice, tomatoes, red bell peppers, scotch bonnet, onions, fried plantain.',
      chefNote:    'Smoked over an open flame for that authentic party-jollof char.',
      badge:       'Signature',
    },
    {
      key:         'fried-rice-plantain',
      name:        'Fried Rice & Plantain',
      category:    'Rice Dishes',
      price:       '€18.00',
      description: 'Nigerian-style fried rice with mixed vegetables and curry seasoning, served with sweet fried plantain.',
      tags:        ['Popular'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #3A4A00 0%, #6B8500 45%, #A8C840 100%)', emoji: '🍚' },
      model:       '/assets/models/fried-rice-plantain.glb',
      scale:       '0.35 0.35 0.35',
      allergens:   [],
      ingredients: 'Rice, mixed vegetables, curry powder, vegetable oil, fried plantain.',
    },
    {
      key:         'white-rice-ayamase',
      name:        'White Rice & Ayamase',
      category:    'Rice Dishes',
      price:       '€20.00',
      description: 'Plain white rice served with ayamase, a spicy green pepper "ofada" stew made with assorted meat and locust beans.',
      tags:        ['Spicy'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #1A3000 0%, #3A5500 45%, #6B8A20 100%)', emoji: '🌶️' },
      model:       '/assets/models/white-rice-ayamase.glb',
      scale:       '0.35 0.35 0.35',
      allergens:   [],
      ingredients: 'White rice, green bell peppers, scotch bonnet, assorted meat, locust beans, palm oil.',
    },
    {
      key:         'white-rice-plantain',
      name:        'White Rice & Plantain',
      category:    'Rice Dishes',
      price:       '€20.00',
      description: 'Plain white rice served with sweet fried plantain, often alongside a stew.',
      tags:        [],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #7A6A2A 0%, #A69245 45%, #D4C580 100%)', emoji: '🍚' },
      allergens:   [],
      ingredients: 'White rice, fried plantain, tomato and pepper stew.',
    },
    {
      key:         'rice-fresh-fish-stew',
      name:        'Rice & Fresh Fish Stew',
      category:    'Rice Dishes',
      price:       'Ask your server',
      description: 'White or jollof rice served with a tomato-based stew made with fresh fish.',
      tags:        [],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #6B1A0A 0%, #B84A28 45%, #E08050 100%)', emoji: '🐟' },
      allergens:   [ALLERGEN.FISH],
      ingredients: 'Rice, tomatoes, peppers, onions, fresh fish.',
    },
    {
      // Not on the live order-now menu as its own line item — added because a
      // real 3D scan exists for this exact plate. Price unconfirmed; get it
      // from the kitchen before this goes live for real customers.
      key:         'rice-beans-designer-stew',
      name:        'Rice & Beans with Designer Stew',
      category:    'Rice Dishes',
      price:       'Ask your server',
      description: 'Steamed white rice and slow-cooked black-eyed beans served with ayamase, a rich, spicy green pepper "designer" stew.',
      tags:        ['Spicy'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #2A3A00 0%, #5C7500 45%, #96B830 100%)', emoji: '🍚' },
      model:       '/assets/models/rice-beans-designer-stew.glb',
      scale:       '0.35 0.35 0.35',
      allergens:   [],
      ingredients: 'White rice, black-eyed peas, green bell peppers, scotch bonnet, palm oil, assorted meat.',
    },

    // ── Soups & Swallow ──
    {
      key:         'egusi-soup-swallow',
      name:        'Egusi Soup with Swallow',
      category:    'Soups & Swallow',
      price:       '€18.00',
      description: 'Melon-seed thickened soup with leafy greens and assorted meat and fish, served with your choice of swallow.',
      tags:        ["Chef's Pick", 'High Protein'],
      image:       '/assets/images/egusi-soup-swallow.jpg',
      placeholder: { gradient: 'linear-gradient(145deg, #4A3000 0%, #7A5500 45%, #C8A040 100%)', emoji: '🍲' },
      allergens:   [ALLERGEN.FISH, ALLERGEN.CRUSTACEAN],
      portion:     'Full bowl of egusi soup with a mound of swallow of your choice.',
      ingredients: 'Ground melon seed (egusi), palm oil, leafy greens, assorted meat, fish, crayfish.',
      chefNote:    'Ground fresh in-house daily. The depth comes from the stockfish, not shortcuts.',
      badge:       "Chef's Pick",
    },
    {
      key:         'amala-gbegiri-ewedu',
      name:        'Amala – Gbegiri & Ewedu',
      category:    'Soups & Swallow',
      price:       '€18.00',
      description: 'Smooth yam-flour swallow served the traditional Yoruba way, with earthy bean soup (gbegiri) and silky jute-leaf soup (ewedu), finished with a stew.',
      tags:        ['Traditional'],
      image:       '/assets/images/amala-gbegiri-ewedu.jpg',
      placeholder: { gradient: 'linear-gradient(145deg, #2E1500 0%, #5C3A10 45%, #8B6030 100%)', emoji: '🥘' },
      allergens:   [],
      portion:     'The full "abula" combo: amala, gbegiri, and ewedu served together.',
      ingredients: 'Yam flour (amala), black-eyed peas (gbegiri), jute leaves (ewedu), locust beans, palm oil, assorted meat.',
      chefNote:    "A Lagos classic. The three components are meant to be mixed together, not eaten separately.",
      badge:       'Traditional',
    },
    {
      key:         'ogbono-soup',
      name:        'Ogbono Soup with Swallow',
      category:    'Soups & Swallow',
      price:       '€17.00',
      description: 'A thick "draw" soup made from ground ogbono (wild mango) seeds, cooked with palm oil, assorted meat, fish and crayfish, served with a swallow.',
      tags:        ['Traditional'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #3A2A00 0%, #6B5000 45%, #A88820 100%)', emoji: '🍲' },
      allergens:   [ALLERGEN.FISH, ALLERGEN.CRUSTACEAN],
      ingredients: 'Ground ogbono seeds, palm oil, assorted meat, fish, crayfish.',
    },
    {
      key:         'bitter-leaf-soup',
      name:        'Bitter Leaf Soup with Swallow',
      category:    'Soups & Swallow',
      price:       '€18.00',
      description: 'Onugbu (bitter leaf) soup cooked with palm oil, assorted meat and fish, thickened with cocoyam, served with a swallow of choice.',
      tags:        ['Traditional'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #1A2E00 0%, #3A5500 45%, #6B8A30 100%)', emoji: '🥬' },
      allergens:   [ALLERGEN.FISH, ALLERGEN.CRUSTACEAN],
      ingredients: 'Bitter leaf, cocoyam, palm oil, assorted meat, fish.',
    },
    {
      key:         'efo-riro-solid',
      name:        'Efo Riro With Solid',
      category:    'Soups & Swallow',
      price:       '€12.00 – €18.00',
      description: "Rich Yoruba vegetable stew of leafy greens and peppers with assorted meat and fish, served with a \"solid\" swallow such as eba, semo, or pounded yam.",
      tags:        ['Traditional'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #142600 0%, #2E4A00 45%, #5C7A20 100%)', emoji: '🥘' },
      model:       '/assets/models/efo-riro-solid.glb',
      scale:       '0.35 0.35 0.35',
      allergens:   [ALLERGEN.FISH, ALLERGEN.CRUSTACEAN],
      ingredients: 'Leafy greens, palm oil, assorted meat, fish, crayfish, swallow.',
    },
    {
      key:         'seafood-okro',
      name:        'Seafood Okro with Swallow',
      category:    'Soups & Swallow',
      price:       '€17.00 – €18.00',
      description: 'Okra soup loaded with prawns, fish and periwinkle, served with a swallow of choice.',
      tags:        [],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #0A3A2A 0%, #1E6B4A 45%, #5CA888 100%)', emoji: '🦐' },
      allergens:   [ALLERGEN.CRUSTACEAN, ALLERGEN.MOLLUSC, ALLERGEN.FISH],
      ingredients: 'Okra, palm oil, prawns, fish, periwinkle, crayfish.',
    },
    {
      key:         'ewa-aganyin-plantain',
      name:        'Ewa Aganyin & Plantain',
      category:    'Soups & Swallow',
      price:       '€20.00',
      description: 'A popular Lagos street-food dish: soft-mashed black-eyed beans in a fiery, smoky pepper sauce, served with sweet fried plantain.',
      tags:        ['Popular'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #4A1400 0%, #8B3400 45%, #C86020 100%)', emoji: '🫘' },
      allergens:   [],
      ingredients: 'Black-eyed peas, dried scotch bonnet, palm oil, fried plantain.',
    },
    {
      key:         'asaro-sauce',
      name:        'Asaro & Sauce',
      category:    'Soups & Swallow',
      price:       '€14.00',
      description: 'Yam pottage cooked down with palm oil, peppers, onions and spices to a soft mash, served with a side of stew.',
      tags:        ['Traditional'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #7A4A00 0%, #C8860A 45%, #E8B840 100%)', emoji: '🍠' },
      allergens:   [],
      ingredients: 'Yam, palm oil, tomatoes, peppers, onions, crayfish.',
    },
    {
      key:         'beans-plantain',
      name:        'Beans & Plantain',
      category:    'Soups & Swallow',
      price:       'Ask your server',
      description: 'Slow-cooked black-eyed beans served with sweet fried ripe plantain.',
      tags:        ['Vegetarian'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #3A2A00 0%, #6B5000 45%, #A88820 100%)', emoji: '🫘' },
      allergens:   [],
      ingredients: 'Black-eyed peas, palm oil, fried plantain, pepper sauce.',
    },

    // ── Pepper Soup ──
    {
      key:         'assorted-meat-pepper-soup',
      name:        'Assorted Meat Pepper Soup',
      category:    'Pepper Soup',
      price:       '€18.00',
      description: 'A hot, spicy broth loaded with assorted meats, simmered in a traditional pepper soup spice blend of uziza and calabash nutmeg.',
      tags:        ['Spicy'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #4A0A00 0%, #8B2000 45%, #C85020 100%)', emoji: '🍜' },
      allergens:   [],
      ingredients: 'Assorted meat/offal, scotch bonnet, uziza, calabash nutmeg, onions.',
    },
    {
      key:         'tilapia-fish-peppersoup',
      name:        'Tilapia Fish Peppersoup',
      category:    'Pepper Soup',
      price:       '€18.00',
      description: 'A light, hot and peppery broth made with tilapia fish and traditional pepper soup spices.',
      tags:        ['Spicy'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #0A3A4A 0%, #1E6B7A 45%, #5CA8B0 100%)', emoji: '🐟' },
      allergens:   [ALLERGEN.FISH],
      ingredients: 'Tilapia, scotch bonnet, uziza, utazi, calabash nutmeg.',
    },

    // ── Grills & Sides ──
    {
      key:         'asun-goatmeat',
      name:        'Asun (Goatmeat)',
      category:    'Grills & Sides',
      price:       '€18.00',
      description: 'Chopped, char-grilled goat meat tossed in a smoky, spicy pepper sauce of habanero, bell peppers, and onions. A popular Nigerian small-chops dish.',
      tags:        ['Spicy', 'Popular'],
      image:       '/assets/images/asun-goatmeat.jpg',
      placeholder: { gradient: 'linear-gradient(145deg, #5C1A00 0%, #8B3A10 45%, #C06030 100%)', emoji: '🔥' },
      model:       '/assets/models/asun-goatmeat.glb',
      scale:       '0.35 0.35 0.35',
      allergens:   [],
      portion:     'A sharing plate of chopped, bite-sized pieces, great as a starter or side.',
      ingredients: 'Goat meat, bell peppers, onions, scotch bonnet, palm/vegetable oil.',
      chefNote:    'Smoked first, then wok-tossed in the pepper sauce right before serving, so it comes out sizzling.',
      badge:       'Popular',
    },
    {
      key:         'dodo-gizzard',
      name:        'Dodo Gizzard',
      category:    'Grills & Sides',
      price:       '€18.00',
      description: 'Sweet fried ripe plantain (dodo) paired with peppered, sautéed chicken gizzards.',
      tags:        ['Spicy'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #4A2400 0%, #8B4A00 45%, #C88020 100%)', emoji: '🍢' },
      allergens:   [],
      ingredients: 'Ripe plantain, chicken gizzard, scotch bonnet, onions.',
    },
    {
      key:         'peppered-turkey',
      name:        'Peppered Turkey',
      category:    'Grills & Sides',
      price:       '€6.50',
      description: 'Fried or grilled turkey pieces tossed in a spicy pepper sauce, commonly served as a starter or party snack.',
      tags:        ['Spicy'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #5C1400 0%, #9A3000 45%, #D06020 100%)', emoji: '🍗' },
      allergens:   [],
      ingredients: 'Turkey, scotch bonnet, bell peppers, onions.',
    },
    {
      key:         'spicy-wings',
      name:        'Spicy Wings',
      category:    'Grills & Sides',
      price:       '€15.50',
      description: 'Chicken wings fried or grilled and tossed in a spicy Nigerian pepper seasoning.',
      tags:        ['Spicy'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #4A0A00 0%, #8B2000 45%, #C85020 100%)', emoji: '🍗' },
      allergens:   [],
      ingredients: 'Chicken wings, scotch bonnet, garlic, ginger.',
    },
    {
      key:         'spicy-hake-fish',
      name:        'Spicy Hake Fish',
      category:    'Grills & Sides',
      price:       '€6.50',
      description: 'Hake fish fillet, fried or grilled with a spicy Nigerian seasoning blend.',
      tags:        ['Spicy'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #0A3A4A 0%, #1E6B7A 45%, #5CA8B0 100%)', emoji: '🐟' },
      allergens:   [ALLERGEN.FISH],
      ingredients: 'Hake fish, scotch bonnet, garlic, ginger.',
    },

    // ── Seafood ──
    {
      key:         'marinated-king-prawn',
      name:        'Marinated King Prawn',
      category:    'Seafood',
      price:       '€15.50',
      description: 'King prawns marinated in a Nigerian pepper spice blend and grilled.',
      tags:        [],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #0A3A2A 0%, #1E6B4A 45%, #5CA888 100%)', emoji: '🦐' },
      allergens:   [ALLERGEN.CRUSTACEAN],
      ingredients: 'King prawns, scotch bonnet, garlic, ginger.',
    },
    {
      key:         'grilled-fish',
      name:        'Grilled Fish',
      category:    'Seafood',
      price:       '€40.00 – €45.00',
      description: 'A whole fish (typically tilapia), marinated in Nigerian spices and grilled. A sharing centrepiece for the table.',
      tags:        ['Sharing'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #0A3A4A 0%, #1E6B7A 45%, #5CA8B0 100%)', emoji: '🐟' },
      allergens:   [ALLERGEN.FISH],
      ingredients: 'Whole fish, scotch bonnet, garlic, ginger, onions.',
    },

    // ── Other Favourites ──
    {
      key:         'chicken-curry-chips',
      name:        'Chicken Curry & Chips',
      category:    'Other Favourites',
      price:       '€15.50',
      description: 'Chicken pieces simmered in a mild curry-spiced sauce, served with a side of chips.',
      tags:        [],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #4A3000 0%, #7A5500 45%, #C8A040 100%)', emoji: '🍛' },
      allergens:   [],
      ingredients: 'Chicken, curry powder, onions, potatoes, vegetable oil.',
    },
    {
      key:         'stir-fry-noodles',
      name:        'Stir Fry Noodles',
      category:    'Other Favourites',
      price:       '€15.50',
      description: 'Stir-fried noodles with mixed vegetables in a Nigerian-Chinese fusion style, often with chicken or shrimp.',
      tags:        [],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #3A2A00 0%, #6B5000 45%, #A88820 100%)', emoji: '🍜' },
      allergens:   [ALLERGEN.GLUTEN],
      ingredients: 'Noodles, mixed vegetables, soy sauce, garlic, ginger, protein.',
    },
    {
      // Not on the live order-now menu as its own line item — added because a
      // real 3D scan exists for this exact plate. Price unconfirmed; get it
      // from the kitchen before this goes live for real customers.
      key:         'spaghetti-jollof-beef-chicken',
      name:        'Spaghetti Jollof with Beef & Chicken',
      category:    'Other Favourites',
      price:       'Ask your server',
      description: 'Spaghetti cooked in a smoky jollof tomato base, served with beef and chicken.',
      tags:        ['Popular'],
      image:       null,
      placeholder: { gradient: 'linear-gradient(145deg, #6B1A0A 0%, #B84A28 45%, #E08050 100%)', emoji: '🍝' },
      model:       '/assets/models/spaghetti-jollof-beef-chicken.glb',
      scale:       '0.35 0.35 0.35',
      allergens:   [ALLERGEN.GLUTEN],
      ingredients: 'Spaghetti, tomatoes, red peppers, scotch bonnet, beef, chicken.',
    },
  ],
};

export default restaurant;
